version: "3.9"
services:
  db:
    build: ./simulation_generator/database/
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./simulation_generator/pgdata:/var/lib/postgresql/data postgres
    
  app :
    build: ./simulation_generator/simulation-app/
    restart: on-failure
    hostname: slurm_host
    depends_on: 
      - db   
volumes:
  pgdata:

